spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/shopaholicdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /shopaholic
  error:
    include-message: ALWAYS

