spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
  datasource:
      url: jdbc:postgresql://localhost:5432/shopaholicdb
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}



server:
  port: 8080
  servlet:
    context-path: /shopaholic
  error:
    include-message: ALWAYS
    include-exception: false
    include-stacktrace: NEVER

